name: Release new version

on:
  workflow_dispatch:
    inputs:
      publish:
        description: Release this version
        type: boolean
        default: false
      publish-pypi:
        description: Package index to publish docs to
        type: choice
        options:
          - none
          - PyPI

env:
  PYPI_PACKAGE: hexdoc-hexparty
  MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
  CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}

permissions:
  contents: read

jobs:
  hexdoc:
    uses: hexdoc-dev/actions/.github/workflows/hexdoc.yml@v1
    permissions:
      contents: write
      pages: read
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with:
      python-version: '3.11'
      release: ${{ inputs.publish }} == 'true'

  publish-docs-pypi:
    runs-on: ubuntu-latest
    needs: hexdoc
    if: needs.hexdoc.outputs.release == 'true'
    environment:
      name: pypi
      url: https://pypi.org/p/${{ env.PYPI_PACKAGE }}
    permissions:
      id-token: write
    steps:
      - name: Download package artifact
        uses: actions/download-artifact@v4
        with:
          name: hexdoc-build
          path: dist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

  publish:
    runs-on: ubuntu-latest
    if: ${{ inputs.publish }} == 'true'
    environment:
      name: publishing
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - uses: gradle/actions/setup-gradle@v4

      - run: chmod +x ./gradlew

      - name: Build mod
        run: ./gradlew build

      - name: Publish mod
        run: ./gradlew forge:publishMods fabric:publishMods

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Get Azure access token
        id: get-token
        run: |
          token=$(az account get-access-token --query accessToken --resource 499b84ac-1321-427f-aa17-267ca6975798 --output tsv)
          echo "::add-mask::$token"
          echo "token=$token" >> "$GITHUB_OUTPUT"

      - name: Publish to ${{ inputs.dry_run && 'Maven Local' || 'Maven' }}
        env:
          MAVEN_PASSWORD: ${{ steps.get-token.outputs.token }}
        run: ./gradlew ${{ inputs.dry_run && 'publishToMavenLocal' || 'publish' }}
