name: Release new version

on:
  workflow_dispatch:
    inputs:
      release:
        description: Release this version
        type: boolean
        default: false
      publish-pypi:
        description: Package index to publish docs to
        type: choice
        options:
          - none
          - PyPI
      dry-run:
        description: Dry Run for Maven Publishing
        type: boolean
        default: false

env:
  PYPI_PACKAGE: hexdoc-hexweb

permissions:
  contents: read

jobs:
  hexdoc:
    uses: hexdoc-dev/actions/.github/workflows/hexdoc.yml@v1
    permissions:
      contents: write
      pages: read
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with:
      python-version: '3.11'
      release: inputs.release

  publish-docs-pypi:
    runs-on: ubuntu-latest
    needs: hexdoc
    if: needs.hexdoc.outputs.release == 'true'
    environment:
      name: pypi
      url: https://pypi.org/p/${{ env.PYPI_PACKAGE }}
    permissions:
      id-token: write
    steps:
      - name: Download package artifact
        uses: actions/download-artifact@v4
        with:
          name: hexdoc-build
          path: dist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

  publish:
    runs-on: ubuntu-latest
    if: inputs.release == 'true'
    environment:
      name: ${{ !inputs.dry_run && 'publishing' || '' }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - uses: gradle/actions/setup-gradle@v4

      - name: Build mod
        run: ./gradlew build

      - name: Publish mod
        run: ./gradlew forge:publishMods fabric:publishMods

      - name: Login to Azure
        if: inputs.dry_run == false
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Get Azure access token
        id: get-token
        if: inputs.dry_run == false
        run: |
          token=$(az account get-access-token --query accessToken --resource 499b84ac-1321-427f-aa17-267ca6975798 --output tsv)
          echo "::add-mask::$token"
          echo "token=$token" >> "$GITHUB_OUTPUT"

      - name: Publish to ${{ inputs.dry_run && 'Maven Local' || 'Maven' }}
        env:
          MAVEN_PASSWORD: ${{ steps.get-token.outputs.token }}
        run: ./gradlew ${{ inputs.dry_run && 'publishToMavenLocal' || 'publish' }}

      - name: Upload dry run artifact
        if: inputs.dry_run
        uses: actions/upload-artifact@v4
        with:
          name: maven-dry-run
          path: ~/.m2/repository/io/github/techtastic
          if-no-files-found: error